
name: Test and Deploy node js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: install npm
      run: npm install
    - name: start server
      run: npm start &
    - name: test npm
      run: npm test

  deploy:
    needs:  build_and_test
    runs-on: ubuntu-latest

    steps:
    - uses: JorgeLNJunior/render-deploy@v1.5.0
      with:
        service_id: ${{ secrets.SERVICE_ID }}
        api_key: ${{ secrets.RENDER_TOKEN }}
        wait_deploy: true
